# GoReleaser configuration
# Documentation: https://goreleaser.com
version: 2

before:
  hooks:
    # Ensure module is tidy
    - go mod tidy

builds:
  - id: nbia-cli
    binary: nbia-data-retriever-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
      - riscv64
    # Skip unsupported combinations
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: riscv64
    # Custom build flags
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildStamp={{.Date}}
      - -X main.gitHash={{.Commit}}
      - -X main.goVersion={{.Env.GO_VERSION}}

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'Features'
      regexp: "^feat"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^fix"
      order: 1
    - title: 'Performance'
      regexp: "^perf"
      order: 2
    - title: 'Refactoring'
      regexp: "^refactor"
      order: 3
    - title: Others
      order: 999

release:
  github:
    owner: GrigoryEvko
    name: NBIA_data_retriever_CLI
  
  # Release notes
  header: |
    ## NBIA Data Retriever CLI v{{ .Version }}
    
    A robust command-line replacement for NBIA Data Retriever with enhanced features and reliability.
    
  footer: |
    ## Installation
    
    Download the appropriate binary for your platform and make it executable:
    
    ```bash
    # Linux/macOS
    chmod +x nbia-data-retriever-cli
    ./nbia-data-retriever-cli --version
    
    # Windows
    nbia-data-retriever-cli.exe --version
    ```
    
    For more information, see the [README](https://github.com/GrigoryEvko/NBIA_data_retriever_CLI#readme).
  
  # Prepend changelog to release notes
  prerelease: auto
  mode: append